name: create_release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'README.md'
      - '.gitignore'
      - '.devcontainer'
      - '.vscode'
      - 'misc'

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "rnacloud_runner"
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
          lfs: 'true'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Run tests
        run: ./run_tests.sh

      - name: Run workflow
        run: ./run_workflow.sh

      - name: Upload DAG
        uses: actions/upload-artifact@v4
        with:
          name: DAG.mmd
          path: output/dag.mmd
          compression-level: 0
          retention-days: 7

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report.html
          path: output/report.html
          compression-level: 0
          retention-days: 7

      - name: Upload timeline
        uses: actions/upload-artifact@v4
        with:
          name: timeline.html
          path: output/timeline.html
          compression-level: 0
          retention-days: 7

      - name: Create version
        id: create_version
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_version.outputs.tag }}
          files: |
            output/grc_fixes_assessment.tsv
            output/splice_site_pop_freq.tsv
            output/*.fasta.gz*
            output/*.gtf.gz*
            output/md5checksums.txt
            output/*.bed
          generate_release_notes: true
          token: ${{ github.token }}