name: pull_request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .devcontainer/**
      - .vscode/**
      - docs/**
      - README.md
      - LICENSE
      - .gitignore
      - .github/workflows/**

jobs:
  pull_request:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "rnacloud_runner"
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
          lfs: 'true'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Run tests
        run: ./run_tests.sh

      - name: Run workflow
        run: ./run_workflow.sh

      - name: Upload DAG
        uses: actions/upload-artifact@v4
        with:
          name: DAG.mmd
          path: output/dag.mmd
          compression-level: 0
          retention-days: 7

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report.html
          path: output/report.html
          compression-level: 0
          retention-days: 7

      - name: Upload timeline
        uses: actions/upload-artifact@v4
        with:
          name: timeline.html
          path: output/timeline.html
          compression-level: 0
          retention-days: 7

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: validation_report.txt
          path: output/validation_report.txt
          compression-level: 0
          retention-days: 7

      - name: Compare md5checksums with latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail

          # get latest release tag
          tag="$(gh api "repos/$REPO/releases/latest" --jq .tag_name)"
          echo "Latest release tag: $tag"

          # fetch output/md5checksums.txt from that tag in the repo (works for private repos)
          tmpfile="$(mktemp)"
          if ! gh api "repos/$REPO/contents/md5checksums.txt?ref=$tag" --jq .content | base64 -d > "$tmpfile" 2>/dev/null; then
            echo "::error No md5checksums.txt found at tag $tag."
            exit 1
          fi

          echo "ðŸ“‘ Comparing files:"
          echo "Generated file (this run):"
          cat output/md5checksums.txt
          echo "--------------------------"
          echo "Release file ($tag):"
          cat "$tmpfile"
          echo "=========================="

          # compare with the one produced in this run
          if cmp -s "output/md5checksums.txt" "$tmpfile"; then
            echo "::notice= md5checksums match latest release ($tag)."
          else
            echo "::noticeâ‰  md5checksums differ from latest release ($tag):"
            diff -u "$tmpfile" "output/md5checksums.txt" || true
          fi