name: pull_request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .devcontainer/**
      - .vscode/**
      - docs/**
      - README.md
      - LICENSE
      - .gitignore
      - .github/workflows/**

jobs:
  pull_request:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "rnacloud_runner"
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
          lfs: 'true'

      - name: Restore source data files if available
        uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: data/
          key: ${{ hashFiles('conf/sources.json') }}

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Run tests
        run: ./run_tests.sh

      - name: Run workflow
        run: ./run_workflow.sh

      - name: save source data files for next use
        uses: actions/cache/save@v4
        id: cache-save
        with:
          path: data/**
          key: ${{ hashFiles('conf/sources.json') }}

      - name: Upload DAG
        uses: actions/upload-artifact@v4
        with:
          name: DAG.mmd
          path: output/dag.mmd
          compression-level: 0
          retention-days: 7

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report.html
          path: output/report.html
          compression-level: 0
          retention-days: 7

      - name: Upload timeline
        uses: actions/upload-artifact@v4
        with:
          name: timeline.html
          path: output/timeline.html
          compression-level: 0
          retention-days: 7

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: validation_report.txt
          path: output/validation_report.txt
          compression-level: 0
          retention-days: 7

      - name: Upload genome build report
        uses: actions/upload-artifact@v4
        with:
          name: genome_and_annotation_report.md
          path: output/genome_and_annotation_report.md
          compression-level: 0
          retention-days: 7

      - name: Compare md5checksums with latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail

          echo "üè∑Ô∏è Get latest release tag"
          tag="$(gh release list --json isLatest,tagName -q '.[] | select(.isLatest == true) | .tagName')"
          echo "Latest release tag: $tag"

          # fetch output/md5checksums.txt from that tag in the repo (works for private repos)
          tmpfile="$(mktemp)"

          echo "‚¨áÔ∏è Downloading md5checksums.txt from release $tag ..."
          gh release download $tag -p 'md5checksums.txt' -O $tmpfile

          if [ ! -f $tmpfile ]; then
            echo "::error No md5checksums.txt found at tag $tag."
            exit 1
          fi

          echo "üîé Comparing files:"
          echo "üìÉ Generated file (this run):"
          cat output/md5checksums.txt
          echo "--------------------------"
          echo "üìÉ Release file ($tag):"
          cat "$tmpfile"
          echo "--------------------------"

          # compare with the one produced in this run
          if cmp -s "output/md5checksums.txt" "$tmpfile"; then
            echo "::notice= md5checksums match latest release ($tag)."
          else
            echo "::notice‚â† md5checksums differ from latest release ($tag):"
            diff -u "$tmpfile" "output/md5checksums.txt" || true
          fi